version: '3.8'

services:
  centre-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://centre_service_db:5432/centredb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=lamaachi
    depends_on:
      - centre_service_db
  centre_service_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=centredb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lamaachi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
