version: '3.8'

services:
  centre-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/centredb
      - SPRING_DATASOURCE_USERNAME=centreuser
      - SPRING_DATASOURCE_PASSWORD=yourpassword
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=centredb
      - POSTGRES_USER=centreuser
      - POSTGRES_PASSWORD=yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
