version: "1.0"
services:
  # Config Server Service
#  config-server:
#    build:
#      context: ./config-server
#    ports:
#      - "8888:8888"
#    environment:
#      SPRING_PROFILES_ACTIVE: native
#      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/app/config-repo
#    volumes:
#      - ./config-repo:/app/config-repo

  # Center Service
  centre-service:
    build:
      context: ./centre-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://center-service-db:5432/centredb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lamaachi
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    depends_on:
#      - config-server
      - center-service-db
  # PostgreSQL Database
  center-service-db:
    image: postgres:13
    environment:
      POSTGRES_DB: centredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lamaachi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
