version: "3.0"
services:
  nginx-service:
    build:
      context: ./nginx-service
      dockerfile: Dockerfile  # Build the custom Nginx image
    container_name: nginx-service
    ports:
      - "8088:80"  # Expose Nginx on port 80
    depends_on:
      - terrain-service
      - centre-service
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  # Eureka server
  discovery-service:
    build:
      context: ./discovery-Service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ADMIN_SERVER_URL: http://admin-server:8080
      EUREKA_SERVER_URL: http://discovery-service:8761/eureka
    networks:
      - app-network

  admin-server:
    build:
      context: ./admin-server
    container_name: admin-server
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ADMIN_SERVER_URL: "http://admin-server:8080"
    networks:
      - app-network
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3

#  config-server:
#    build:
#      context: ./config-server
#    container_name: config-server
#    ports:
#      - "9000:9000"
#    environment:
#      SPRING_PROFILES_ACTIVE: native
#      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: https://github.com/lamaachi/sporting-config-repo
#    volumes:
#      - ./config-repo:/app/config-repo
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://config-server:9000/actuator/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#    networks:
#      - app-network

  terrain-service:
    build:
      context: ./terain-service
    container_name: terrain-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://terain-service-db:5432/teraindb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lamaachi
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: terain-service
      ADMIN_SERVER_URL: http://admin-server:8080

    ports:
      - "8084:8084"
    networks:
      - app-network
#  auth-service:
#    build:
#      context: ./auth-service
#    container_name: auth-service
#    ports:
#      - "8880:8880"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      SPRING_WEB_CORS_ALLOWED-ORIGINS: http://localhost:3000
#      SPRING_WEB_CORS_ALLOWED-METHODS: "*"
#      SPRING_WEB_CORS_ALLOWED-HEADERS: "*"
#      SPRING_WEB_CORS_ALLOW-CREDENTIALS: "true"
#      AWS_COGNITO_USERPOOLID: us-east-1_EFk0O4Bg5
#      AWS_COGNITO_CLIENTID: 5a6cmfelb5uep60k3f6irfvjid
#      AWS_COGNITO_CLIENTSECRET: 1mkuud3cnjj0q2nnoe7lai11davuf3c4edjgpirmj1r3rl5ubumu
#      AWS_COGNITO_REGION: us-east-1
#      COGNITO_ENDPOINT: https://cognito-idp.us-east-1.amazonaws.com/
#    networks:
#      - app-network

  centre-service:
    build:
      context: ./centre-service
    container_name: centre-service
    depends_on:
#      - config-server
      - rabbitmq
      - center-service-db
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://center-service-db:5432/centredb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lamaachi
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: centre-service
      ADMIN_SERVER_URL: http://admin-server:8080
    networks:
      - app-network
  center-service-db:
    image: postgres:13
    container_name: center-service-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_DB: centredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lamaachi
    ports:
      - "5433:5432"
    volumes:
      - postgres_center_data:/var/lib/postgresql/data
    networks:
      - app-network

  terain-service-db:
    image: postgres:13
    container_name: terain-service-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_DB: teraindb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lamaachi

    ports:
      - "5434:5432"
    volumes:
      - postgres_terain_data:/var/lib/postgresql/data
    networks:
      - app-network

#  api-gateway:
#    build:
#      context: ./apigatway
#    container_name: api-gateway
#    ports:
#      - "8082:8082"
#    depends_on:
#      - discovery-service
#      - centre-service
#      - terrain-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      SPRING_CLOUD_GATEWAY_ROUTES_TERRAIN_URI: http://terain-service:8085
#      SPRING_CLOUD_GATEWAY_ROUTES_CENTRE_URI: http://centre-service:8084
#      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://discovery-service:8761/eureka/
#    networks:
#      - app-network


  reservation-service:
    build:
      context: ./reservation-service
    container_name: reservation-service
    depends_on:
      - reservation-service-db
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://reservation-service-db:5432/reservation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 00990099
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

    networks:
      - app-network


  reservation-service-db:
    image: postgres:13
    container_name: reservation-service-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_DB: reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 00990099
    ports:
      - "5435:5432"
    volumes:
      - postgres_reservation_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_center_data:
  postgres_terain_data:
  postgres_reservation_data:

