
spring:
  application:
    name: registry-service

server:
  port: 8761

eureka:
  instance:
    secure-virtual-host-name: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
