server:
  port: 8761  # Eureka server will be accessible on this port

eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false  # Disable self-preservation to prevent Eureka from refusing to register services
    eviction-interval-timer-in-ms: 5000  # Time interval to check expired instances

spring:
  application:
    name: discovery-service  # The name of the Eureka server
  cloud:
    discovery:
      enabled: true
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8080}