spring:
  application:
    name: terain-service
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8889
  kafka:
    bootstrap-servers: localhost:9092