server:
  port: 8888 # Port for the config server

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lamaachi/sporting-config-repo # Git repository for configuration files
          default-label: main # Branch containing configuration files
